# Qwen2.5-1.5B-Instruct Inference
Loading and running the Qwen/Qwen2.5-1.5B-Instruct model using 🤗 Transformers.

In [1]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Define and create the directory path
drive_path = "/content/drive/MyDrive/msc/models"
os.makedirs(drive_path, exist_ok=True)

print(f"Directory is ready at: {drive_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Directory is ready at: /content/drive/MyDrive/msc/models

In [2]:
%pip install -q trl transformers datasets accelerate peft optuna bitsandbytes wandb
!pip install torchao -U

Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.17.0)

In [3]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,TrainerCallback
import torch
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTConfig, SFTTrainer
import optuna
import wandb
model_id = 'Qwen/Qwen2.5-1.5B-Instruct'

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [4]:
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Qwen uses eos_token as pad — required to avoid warnings
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
print('Tokenizer loaded ✓')

Tokenizer loaded ✓

In [5]:
from datasets import load_dataset
import re

TRAINING_PATH = "/content/drive/MyDrive/Msc/data/final_combined_dataset_combined_instructions.jsonl"

# def contains_english_letters(text):
#     return bool(re.search('[a-zA-Z]', text))

def format_prompts(batch):
    formatted_texts = []
    for q, a in zip(batch["instruction"], batch["response_hebrew"]):
        # Use Qwen's native chat template
        messages = [
            {"role": "user",      "content": q},
            {"role": "assistant", "content": a},
        ]
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=False
        )
        formatted_texts.append(text)
    return {"text": formatted_texts}

# Load → filter → split → format (correct order)
dataset = load_dataset("json", data_files=TRAINING_PATH, split="train")
# dataset = dataset.filter(lambda x: not contains_english_letters(x["answer_heb"]))
dataset = dataset.shuffle(seed=42)

split_dataset   = dataset.train_test_split(test_size=0.2, seed=42)
formatted_dataset = split_dataset.map(format_prompts, batched=True)

print(f"Train: {len(formatted_dataset['train'])} | Eval: {len(formatted_dataset['test'])}")

Train: 4298 | Eval: 1075

In [ ]:
from google.colab import userdata
import os
os.environ["WANDB_API_KEY"] = userdata.get("WANDB_API_KEY")

class LogLoraParamsCallback(TrainerCallback):
    def on_train_begin(self, args, state, control, **kwargs):
        # Log the LoRA params for this trial to W&B
        wandb.config.update({
            "lora_r":       _current_lora_params.get("lora_r"),
            "lora_alpha":   _current_lora_params.get("lora_alpha"),
            "lora_dropout": _current_lora_params.get("lora_dropout"),
        })

    def on_train_end(self, args, state, control, **kwargs):
        wandb.finish()

wandb.login()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: talsomech (talsomech-bar-ilan-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [ ]:

# QLoRA: 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",           # nf4 > fp4 for LLMs
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,      # saves extra VRAM
)

_current_lora_params = {}
def my_hp_space(trial):
    _current_lora_params["lora_r"]       = trial.suggest_categorical("lora_r", [4, 8, 16])
    _current_lora_params["lora_alpha"]   = trial.suggest_categorical("lora_alpha", [8, 16, 32])
    _current_lora_params["lora_dropout"] = trial.suggest_float("lora_dropout", 0.05, 0.3)

    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 5e-5, log=True),
        "warmup_ratio": trial.suggest_float("warmup_ratio", 0.03, 0.10),
        "weight_decay": trial.suggest_float("weight_decay", 0.0, 0.1),
    }
def compute_objective(metrics):
    return metrics["eval_loss"]

def model_init(trial):
    r = _current_lora_params.get("lora_r", 8)
    alpha = _current_lora_params.get("lora_alpha", 16)
    dropout = _current_lora_params.get("lora_dropout", 0.05)
    base_model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto",
    )
    base_model = prepare_model_for_kbit_training(base_model)
    peft_config = LoraConfig(
         r=r,
         lora_alpha=alpha,
         lora_dropout=dropout,
         target_modules="all-linear",
         bias="none",
         task_type="CAUSAL_LM",
     )
    return get_peft_model(base_model, peft_config)

In [ ]:
training_args = SFTConfig(
    output_dir="/content/drive/MyDrive/Msc/models",
    max_steps=300,
    # max_seq_length=512,
    logging_steps=100,
    save_steps=200,
    eval_strategy="steps",
    eval_steps=50,
    fp16=True,
    dataset_text_field="text",
    disable_tqdm=True,
    report_to="wandb",
    run_name="qwen-qlora-final"
)

trainer=SFTTrainer(
    model=model_init(None),
    args=training_args,
    train_dataset=formatted_dataset["train"],
    eval_dataset=formatted_dataset["test"],
    peft_config=None,
    processing_class=tokenizer,
    callbacks=[LogLoraParamsCallback()],
    )
trainer.model_init=model_init

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Adding EOS to train dataset:   0%|          | 0/4500 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/4500 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/500 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/500 [00:00<?, ? examples/s]

In [ ]:
best_run = trainer.hyperparameter_search(
    hp_space=my_hp_space,
    compute_objective=compute_objective,
    n_trials=10,                # Number of total tuning combinations to try
    direction="minimize",       # We want to minimize eval_loss
    backend="optuna",
)
print("Best run:", best_run)
print("Best hyperparameters:", best_run.hyperparameters)

[I 2026-05-30 14:59:08,276] A new study created in memory with name: no-name-7eaa8e92-8245-4672-824f-6fac55e01c29
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '4.102', 'eval_runtime': '0.6234', 'eval_samples_per_second': '22.46', 'eval_steps_per_second': '3.208', 'eval_entropy': '3.288', 'eval_num_tokens': '3.031e+04', 'eval_mean_token_accuracy': '0.3782', 'epoch': '3.125'}
{'loss': '4.119', 'grad_norm': '2.924', 'learning_rate': '1.083e-06', 'entropy': '3.171', 'num_tokens': '6.01e+04', 'mean_token_accuracy': '0.4063', 'epoch': '6.25'}
{'eval_loss': '3.811', 'eval_runtime': '0.629', 'eval_samples_per_second': '22.26', 'eval_steps_per_second': '3.18', 'eval_entropy': '3.256', 'eval_num_tokens': '6.01e+04', 'eval_mean_token_accuracy': '0.4446', 'epoch': '6.25'}
{'eval_loss': '3.59', 'eval_runtime': '0.6506', 'eval_samples_per_second': '21.52', 'eval_steps_per_second': '3.074', 'eval_entropy': '3.227', 'eval_num_tokens': '8.958e+04', 'eval_mean_token_accuracy': '0.4479', 'epoch': '9.375'}
{'loss': '3.563', 'grad_norm': '2.175', 'learning_rate': '5.441e-07', 'entropy': '3.137', 'num_tokens': '1.193e+05', 'mean_token_accuracy': '0.4782', 'epoch': '12.5'}
{'eval_loss': '3.463', 'eval_runtime': '0.6197', 'eval_samples_per_second': '22.59', 'eval_steps_per_second': '3.227', 'eval_entropy': '3.207', 'eval_num_tokens': '1.193e+05', 'eval_mean_token_accuracy': '0.4641', 'epoch': '12.5'}
{'eval_loss': '3.4', 'eval_runtime': '0.6226', 'eval_samples_per_second': '22.48', 'eval_steps_per_second': '3.212', 'eval_entropy': '3.2', 'eval_num_tokens': '1.489e+05', 'eval_mean_token_accuracy': '0.4649', 'epoch': '15.62'}
{'loss': '3.337', 'grad_norm': '2.044', 'learning_rate': '5.387e-09', 'entropy': '3.116', 'num_tokens': '1.786e+05', 'mean_token_accuracy': '0.4901', 'epoch': '18.75'}
{'eval_loss': '3.381', 'eval_runtime': '0.6175', 'eval_samples_per_second': '22.67', 'eval_steps_per_second': '3.239', 'eval_entropy': '3.197', 'eval_num_tokens': '1.786e+05', 'eval_mean_token_accuracy': '0.4659', 'epoch': '18.75'}
{'train_runtime': '344.6', 'train_samples_per_second': '6.964', 'train_steps_per_second': '0.871', 'train_loss': '3.673', 'epoch': '18.75'}

[I 2026-05-30 15:05:00,266] Trial 0 finished with value: 3.3809375762939453 and parameters: {'lora_r': 16, 'lora_alpha': 16, 'lora_dropout': 0.27732920472179956, 'learning_rate': 1.6160988883677513e-06, 'warmup_ratio': 0.07645836138382692, 'weight_decay': 0.08790829450324014}. Best is trial 0 with value: 3.3809375762939453.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '4.26', 'eval_runtime': '0.6269', 'eval_samples_per_second': '22.33', 'eval_steps_per_second': '3.19', 'eval_entropy': '3.246', 'eval_num_tokens': '2.082e+05', 'eval_mean_token_accuracy': '0.3638', 'epoch': '3.125'}
{'loss': '4.27', 'grad_norm': '1.581', 'learning_rate': '1.23e-06', 'entropy': '3.151', 'num_tokens': '2.38e+05', 'mean_token_accuracy': '0.3872', 'epoch': '6.25'}
{'eval_loss': '4.038', 'eval_runtime': '0.6158', 'eval_samples_per_second': '22.73', 'eval_steps_per_second': '3.248', 'eval_entropy': '3.284', 'eval_num_tokens': '2.38e+05', 'eval_mean_token_accuracy': '0.3797', 'epoch': '6.25'}
{'eval_loss': '3.876', 'eval_runtime': '0.6135', 'eval_samples_per_second': '22.82', 'eval_steps_per_second': '3.26', 'eval_entropy': '3.261', 'eval_num_tokens': '2.675e+05', 'eval_mean_token_accuracy': '0.4392', 'epoch': '9.375'}
{'loss': '3.855', 'grad_norm': '1.505', 'learning_rate': '6.179e-07', 'entropy': '3.171', 'num_tokens': '2.972e+05', 'mean_token_accuracy': '0.4481', 'epoch': '12.5'}
{'eval_loss': '3.76', 'eval_runtime': '0.6461', 'eval_samples_per_second': '21.67', 'eval_steps_per_second': '3.096', 'eval_entropy': '3.24', 'eval_num_tokens': '2.972e+05', 'eval_mean_token_accuracy': '0.4446', 'epoch': '12.5'}
{'eval_loss': '3.694', 'eval_runtime': '0.621', 'eval_samples_per_second': '22.55', 'eval_steps_per_second': '3.221', 'eval_entropy': '3.234', 'eval_num_tokens': '3.269e+05', 'eval_mean_token_accuracy': '0.4446', 'epoch': '15.62'}
{'loss': '3.646', 'grad_norm': '1.6', 'learning_rate': '6.118e-09', 'entropy': '3.151', 'num_tokens': '3.565e+05', 'mean_token_accuracy': '0.4701', 'epoch': '18.75'}
{'eval_loss': '3.673', 'eval_runtime': '0.637', 'eval_samples_per_second': '21.98', 'eval_steps_per_second': '3.14', 'eval_entropy': '3.233', 'eval_num_tokens': '3.565e+05', 'eval_mean_token_accuracy': '0.4464', 'epoch': '18.75'}
{'train_runtime': '326.7', 'train_samples_per_second': '7.346', 'train_steps_per_second': '0.918', 'train_loss': '3.924', 'epoch': '18.75'}

[I 2026-05-30 15:10:36,230] Trial 1 finished with value: 3.6731951236724854 and parameters: {'lora_r': 16, 'lora_alpha': 8, 'lora_dropout': 0.15013704272758532, 'learning_rate': 1.8353903576562912e-06, 'warmup_ratio': 0.07366178322049341, 'weight_decay': 0.04947910041802779}. Best is trial 0 with value: 3.3809375762939453.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '3.117', 'eval_runtime': '0.6135', 'eval_samples_per_second': '22.82', 'eval_steps_per_second': '3.26', 'eval_entropy': '3.129', 'eval_num_tokens': '3.862e+05', 'eval_mean_token_accuracy': '0.4678', 'epoch': '3.125'}
{'loss': '3.178', 'grad_norm': '4.063', 'learning_rate': '6.372e-06', 'entropy': '3.028', 'num_tokens': '4.16e+05', 'mean_token_accuracy': '0.4973', 'epoch': '6.25'}
{'eval_loss': '2.593', 'eval_runtime': '0.6212', 'eval_samples_per_second': '22.54', 'eval_steps_per_second': '3.22', 'eval_entropy': '2.803', 'eval_num_tokens': '4.16e+05', 'eval_mean_token_accuracy': '0.5609', 'epoch': '6.25'}
{'eval_loss': '2.384', 'eval_runtime': '0.7008', 'eval_samples_per_second': '19.98', 'eval_steps_per_second': '2.854', 'eval_entropy': '2.623', 'eval_num_tokens': '4.455e+05', 'eval_mean_token_accuracy': '0.5798', 'epoch': '9.375'}
{'loss': '2.258', 'grad_norm': '3.911', 'learning_rate': '3.202e-06', 'entropy': '2.539', 'num_tokens': '4.751e+05', 'mean_token_accuracy': '0.6102', 'epoch': '12.5'}
{'eval_loss': '2.234', 'eval_runtime': '0.622', 'eval_samples_per_second': '22.51', 'eval_steps_per_second': '3.215', 'eval_entropy': '2.581', 'eval_num_tokens': '4.751e+05', 'eval_mean_token_accuracy': '0.5824', 'epoch': '12.5'}
{'eval_loss': '2.123', 'eval_runtime': '0.623', 'eval_samples_per_second': '22.47', 'eval_steps_per_second': '3.21', 'eval_entropy': '2.555', 'eval_num_tokens': '5.048e+05', 'eval_mean_token_accuracy': '0.611', 'epoch': '15.62'}
{'loss': '1.981', 'grad_norm': '2.903', 'learning_rate': '3.17e-08', 'entropy': '2.453', 'num_tokens': '5.344e+05', 'mean_token_accuracy': '0.6364', 'epoch': '18.75'}
{'eval_loss': '2.085', 'eval_runtime': '0.6404', 'eval_samples_per_second': '21.86', 'eval_steps_per_second': '3.123', 'eval_entropy': '2.541', 'eval_num_tokens': '5.344e+05', 'eval_mean_token_accuracy': '0.6173', 'epoch': '18.75'}
{'train_runtime': '323', 'train_samples_per_second': '7.43', 'train_steps_per_second': '0.929', 'train_loss': '2.472', 'epoch': '18.75'}

[I 2026-05-30 15:16:07,102] Trial 2 finished with value: 2.085254192352295 and parameters: {'lora_r': 4, 'lora_alpha': 16, 'lora_dropout': 0.064750534675226, 'learning_rate': 9.509934768871201e-06, 'warmup_ratio': 0.06838987731765853, 'weight_decay': 0.09083884681136661}. Best is trial 2 with value: 2.085254192352295.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '2.442', 'eval_runtime': '0.6569', 'eval_samples_per_second': '21.31', 'eval_steps_per_second': '3.045', 'eval_entropy': '2.652', 'eval_num_tokens': '5.641e+05', 'eval_mean_token_accuracy': '0.5743', 'epoch': '3.125'}
{'loss': '2.527', 'grad_norm': '2.057', 'learning_rate': '1.725e-05', 'entropy': '2.694', 'num_tokens': '5.939e+05', 'mean_token_accuracy': '0.5744', 'epoch': '6.25'}
{'eval_loss': '1.883', 'eval_runtime': '0.6183', 'eval_samples_per_second': '22.64', 'eval_steps_per_second': '3.235', 'eval_entropy': '2.37', 'eval_num_tokens': '5.939e+05', 'eval_mean_token_accuracy': '0.6466', 'epoch': '6.25'}
{'eval_loss': '1.785', 'eval_runtime': '0.6275', 'eval_samples_per_second': '22.31', 'eval_steps_per_second': '3.187', 'eval_entropy': '2.241', 'eval_num_tokens': '6.234e+05', 'eval_mean_token_accuracy': '0.6692', 'epoch': '9.375'}
{'loss': '1.576', 'grad_norm': '3.178', 'learning_rate': '8.666e-06', 'entropy': '2.114', 'num_tokens': '6.531e+05', 'mean_token_accuracy': '0.6966', 'epoch': '12.5'}
{'eval_loss': '1.749', 'eval_runtime': '1.525', 'eval_samples_per_second': '9.181', 'eval_steps_per_second': '1.312', 'eval_entropy': '2.154', 'eval_num_tokens': '6.531e+05', 'eval_mean_token_accuracy': '0.671', 'epoch': '12.5'}
{'eval_loss': '1.733', 'eval_runtime': '1.045', 'eval_samples_per_second': '13.39', 'eval_steps_per_second': '1.914', 'eval_entropy': '2.122', 'eval_num_tokens': '6.827e+05', 'eval_mean_token_accuracy': '0.6722', 'epoch': '15.62'}
{'loss': '1.398', 'grad_norm': '2.808', 'learning_rate': '8.58e-08', 'entropy': '1.969', 'num_tokens': '7.124e+05', 'mean_token_accuracy': '0.7237', 'epoch': '18.75'}
{'eval_loss': '1.727', 'eval_runtime': '0.6144', 'eval_samples_per_second': '22.79', 'eval_steps_per_second': '3.255', 'eval_entropy': '2.105', 'eval_num_tokens': '7.124e+05', 'eval_mean_token_accuracy': '0.6733', 'epoch': '18.75'}
{'train_runtime': '371.3', 'train_samples_per_second': '6.464', 'train_steps_per_second': '0.808', 'train_loss': '1.834', 'epoch': '18.75'}

[I 2026-05-30 15:22:26,365] Trial 3 finished with value: 1.7274423837661743 and parameters: {'lora_r': 4, 'lora_alpha': 16, 'lora_dropout': 0.29372399126429133, 'learning_rate': 2.5740051786786567e-05, 'warmup_ratio': 0.08941637797323801, 'weight_decay': 0.07215405255496064}. Best is trial 3 with value: 1.7274423837661743.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '3.53', 'eval_runtime': '0.6513', 'eval_samples_per_second': '21.5', 'eval_steps_per_second': '3.071', 'eval_entropy': '3.21', 'eval_num_tokens': '7.42e+05', 'eval_mean_token_accuracy': '0.4487', 'epoch': '3.125'}
{'loss': '3.576', 'grad_norm': '2.235', 'learning_rate': '5.873e-06', 'entropy': '3.136', 'num_tokens': '7.718e+05', 'mean_token_accuracy': '0.4577', 'epoch': '6.25'}
{'eval_loss': '3.035', 'eval_runtime': '0.6183', 'eval_samples_per_second': '22.64', 'eval_steps_per_second': '3.235', 'eval_entropy': '3.125', 'eval_num_tokens': '7.718e+05', 'eval_mean_token_accuracy': '0.4718', 'epoch': '6.25'}
{'eval_loss': '2.756', 'eval_runtime': '0.6195', 'eval_samples_per_second': '22.6', 'eval_steps_per_second': '3.228', 'eval_entropy': '2.969', 'eval_num_tokens': '8.013e+05', 'eval_mean_token_accuracy': '0.5167', 'epoch': '9.375'}
{'loss': '2.682', 'grad_norm': '2.469', 'learning_rate': '2.951e-06', 'entropy': '2.89', 'num_tokens': '8.31e+05', 'mean_token_accuracy': '0.5514', 'epoch': '12.5'}
{'eval_loss': '2.644', 'eval_runtime': '0.6236', 'eval_samples_per_second': '22.45', 'eval_steps_per_second': '3.207', 'eval_entropy': '2.853', 'eval_num_tokens': '8.31e+05', 'eval_mean_token_accuracy': '0.5598', 'epoch': '12.5'}
{'eval_loss': '2.584', 'eval_runtime': '0.62', 'eval_samples_per_second': '22.58', 'eval_steps_per_second': '3.226', 'eval_entropy': '2.79', 'eval_num_tokens': '8.607e+05', 'eval_mean_token_accuracy': '0.5734', 'epoch': '15.62'}
{'loss': '2.465', 'grad_norm': '3.128', 'learning_rate': '2.922e-08', 'entropy': '2.701', 'num_tokens': '8.903e+05', 'mean_token_accuracy': '0.6013', 'epoch': '18.75'}
{'eval_loss': '2.565', 'eval_runtime': '0.6184', 'eval_samples_per_second': '22.64', 'eval_steps_per_second': '3.234', 'eval_entropy': '2.769', 'eval_num_tokens': '8.903e+05', 'eval_mean_token_accuracy': '0.5734', 'epoch': '18.75'}
{'train_runtime': '341.4', 'train_samples_per_second': '7.029', 'train_steps_per_second': '0.879', 'train_loss': '2.907', 'epoch': '18.75'}

[I 2026-05-30 15:28:16,029] Trial 4 finished with value: 2.564779043197632 and parameters: {'lora_r': 4, 'lora_alpha': 8, 'lora_dropout': 0.19515526207582595, 'learning_rate': 8.765768320881214e-06, 'warmup_ratio': 0.06857295704020785, 'weight_decay': 0.002707124162529873}. Best is trial 3 with value: 1.7274423837661743.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '3.732', 'eval_runtime': '0.6182', 'eval_samples_per_second': '22.65', 'eval_steps_per_second': '3.235', 'eval_entropy': '3.251', 'eval_num_tokens': '9.2e+05', 'eval_mean_token_accuracy': '0.4464', 'epoch': '3.125'}

[I 2026-05-30 15:29:15,249] Trial 5 pruned.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{'eval_loss': '4.331', 'eval_runtime': '0.6181', 'eval_samples_per_second': '22.65', 'eval_steps_per_second': '3.236', 'eval_entropy': '3.222', 'eval_num_tokens': '9.497e+05', 'eval_mean_token_accuracy': '0.363', 'epoch': '3.125'}

[I 2026-05-30 15:30:13,813] Trial 6 pruned.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

{'eval_loss': '3.404', 'eval_runtime': '0.6166', 'eval_samples_per_second': '22.7', 'eval_steps_per_second': '3.243', 'eval_entropy': '3.2', 'eval_num_tokens': '9.793e+05', 'eval_mean_token_accuracy': '0.4659', 'epoch': '3.125'}
{'loss': '3.475', 'grad_norm': '1.678', 'learning_rate': '7.195e-06', 'entropy': '3.13', 'num_tokens': '1.009e+06', 'mean_token_accuracy': '0.4307', 'epoch': '6.25'}
{'eval_loss': '2.891', 'eval_runtime': '0.6363', 'eval_samples_per_second': '22', 'eval_steps_per_second': '3.143', 'eval_entropy': '3.086', 'eval_num_tokens': '1.009e+06', 'eval_mean_token_accuracy': '0.5112', 'epoch': '6.25'}
{'eval_loss': '2.65', 'eval_runtime': '0.6159', 'eval_samples_per_second': '22.73', 'eval_steps_per_second': '3.247', 'eval_entropy': '2.855', 'eval_num_tokens': '1.039e+06', 'eval_mean_token_accuracy': '0.5601', 'epoch': '9.375'}
{'loss': '2.559', 'grad_norm': '2.045', 'learning_rate': '3.616e-06', 'entropy': '2.78', 'num_tokens': '1.068e+06', 'mean_token_accuracy': '0.5799', 'epoch': '12.5'}
{'eval_loss': '2.537', 'eval_runtime': '0.619', 'eval_samples_per_second': '22.62', 'eval_steps_per_second': '3.231', 'eval_entropy': '2.732', 'eval_num_tokens': '1.068e+06', 'eval_mean_token_accuracy': '0.5752', 'epoch': '12.5'}
{'eval_loss': '2.481', 'eval_runtime': '0.6134', 'eval_samples_per_second': '22.82', 'eval_steps_per_second': '3.261', 'eval_entropy': '2.676', 'eval_num_tokens': '1.098e+06', 'eval_mean_token_accuracy': '0.576', 'epoch': '15.62'}
{'loss': '2.354', 'grad_norm': '2.307', 'learning_rate': '3.58e-08', 'entropy': '2.582', 'num_tokens': '1.128e+06', 'mean_token_accuracy': '0.6071', 'epoch': '18.75'}
{'eval_loss': '2.463', 'eval_runtime': '0.6143', 'eval_samples_per_second': '22.79', 'eval_steps_per_second': '3.256', 'eval_entropy': '2.667', 'eval_num_tokens': '1.128e+06', 'eval_mean_token_accuracy': '0.5749', 'epoch': '18.75'}
{'train_runtime': '302', 'train_samples_per_second': '7.947', 'train_steps_per_second': '0.993', 'train_loss': '2.796', 'epoch': '18.75'}

[I 2026-05-30 15:35:23,332] Trial 7 finished with value: 2.463454008102417 and parameters: {'lora_r': 8, 'lora_alpha': 8, 'lora_dropout': 0.24645974371477547, 'learning_rate': 1.073937542987782e-05, 'warmup_ratio': 0.04740081505471515, 'weight_decay': 0.09211804812276256}. Best is trial 3 with value: 1.7274423837661743.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '2.203', 'eval_runtime': '0.6446', 'eval_samples_per_second': '21.72', 'eval_steps_per_second': '3.103', 'eval_entropy': '2.539', 'eval_num_tokens': '1.157e+06', 'eval_mean_token_accuracy': '0.5978', 'epoch': '3.125'}
{'loss': '2.325', 'grad_norm': '2.056', 'learning_rate': '2.335e-05', 'entropy': '2.571', 'num_tokens': '1.187e+06', 'mean_token_accuracy': '0.6018', 'epoch': '6.25'}
{'eval_loss': '1.787', 'eval_runtime': '0.6152', 'eval_samples_per_second': '22.76', 'eval_steps_per_second': '3.251', 'eval_entropy': '2.235', 'eval_num_tokens': '1.187e+06', 'eval_mean_token_accuracy': '0.671', 'epoch': '6.25'}
{'eval_loss': '1.729', 'eval_runtime': '0.6173', 'eval_samples_per_second': '22.68', 'eval_steps_per_second': '3.24', 'eval_entropy': '2.103', 'eval_num_tokens': '1.217e+06', 'eval_mean_token_accuracy': '0.6719', 'epoch': '9.375'}
{'loss': '1.383', 'grad_norm': '2.737', 'learning_rate': '1.174e-05', 'entropy': '1.941', 'num_tokens': '1.246e+06', 'mean_token_accuracy': '0.7269', 'epoch': '12.5'}
{'eval_loss': '1.711', 'eval_runtime': '0.6288', 'eval_samples_per_second': '22.26', 'eval_steps_per_second': '3.181', 'eval_entropy': '1.99', 'eval_num_tokens': '1.246e+06', 'eval_mean_token_accuracy': '0.6674', 'epoch': '12.5'}
{'eval_loss': '1.705', 'eval_runtime': '0.6154', 'eval_samples_per_second': '22.75', 'eval_steps_per_second': '3.25', 'eval_entropy': '1.941', 'eval_num_tokens': '1.276e+06', 'eval_mean_token_accuracy': '0.6706', 'epoch': '15.62'}
{'loss': '1.154', 'grad_norm': '2.917', 'learning_rate': '1.162e-07', 'entropy': '1.737', 'num_tokens': '1.306e+06', 'mean_token_accuracy': '0.7649', 'epoch': '18.75'}
{'eval_loss': '1.706', 'eval_runtime': '0.6327', 'eval_samples_per_second': '22.13', 'eval_steps_per_second': '3.161', 'eval_entropy': '1.921', 'eval_num_tokens': '1.306e+06', 'eval_mean_token_accuracy': '0.6728', 'epoch': '18.75'}
{'train_runtime': '300', 'train_samples_per_second': '8.001', 'train_steps_per_second': '1', 'train_loss': '1.62', 'epoch': '18.75'}

[I 2026-05-30 15:40:30,644] Trial 8 finished with value: 1.70637047290802 and parameters: {'lora_r': 4, 'lora_alpha': 16, 'lora_dropout': 0.13482101379864803, 'learning_rate': 3.48576351528276e-05, 'warmup_ratio': 0.06349163207497396, 'weight_decay': 0.024825698786720952}. Best is trial 8 with value: 1.70637047290802.

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

{'eval_loss': '2.343', 'eval_runtime': '0.6334', 'eval_samples_per_second': '22.1', 'eval_steps_per_second': '3.157', 'eval_entropy': '2.587', 'eval_num_tokens': '1.335e+06', 'eval_mean_token_accuracy': '0.5802', 'epoch': '3.125'}
{'loss': '2.453', 'grad_norm': '3.202', 'learning_rate': '1.138e-05', 'entropy': '2.638', 'num_tokens': '1.365e+06', 'mean_token_accuracy': '0.5854', 'epoch': '6.25'}
{'eval_loss': '1.842', 'eval_runtime': '0.6175', 'eval_samples_per_second': '22.67', 'eval_steps_per_second': '3.239', 'eval_entropy': '2.306', 'eval_num_tokens': '1.365e+06', 'eval_mean_token_accuracy': '0.6558', 'epoch': '6.25'}
{'eval_loss': '1.769', 'eval_runtime': '0.6283', 'eval_samples_per_second': '22.28', 'eval_steps_per_second': '3.183', 'eval_entropy': '2.2', 'eval_num_tokens': '1.394e+06', 'eval_mean_token_accuracy': '0.6677', 'epoch': '9.375'}
{'loss': '1.512', 'grad_norm': '4.658', 'learning_rate': '5.717e-06', 'entropy': '2.06', 'num_tokens': '1.424e+06', 'mean_token_accuracy': '0.7064', 'epoch': '12.5'}
{'eval_loss': '1.739', 'eval_runtime': '0.6214', 'eval_samples_per_second': '22.53', 'eval_steps_per_second': '3.218', 'eval_entropy': '2.124', 'eval_num_tokens': '1.424e+06', 'eval_mean_token_accuracy': '0.6733', 'epoch': '12.5'}
{'eval_loss': '1.726', 'eval_runtime': '0.6181', 'eval_samples_per_second': '22.65', 'eval_steps_per_second': '3.235', 'eval_entropy': '2.088', 'eval_num_tokens': '1.454e+06', 'eval_mean_token_accuracy': '0.6708', 'epoch': '15.62'}
{'loss': '1.337', 'grad_norm': '4.387', 'learning_rate': '5.66e-08', 'entropy': '1.917', 'num_tokens': '1.483e+06', 'mean_token_accuracy': '0.7338', 'epoch': '18.75'}
{'eval_loss': '1.722', 'eval_runtime': '0.6233', 'eval_samples_per_second': '22.46', 'eval_steps_per_second': '3.209', 'eval_entropy': '2.07', 'eval_num_tokens': '1.483e+06', 'eval_mean_token_accuracy': '0.6704', 'epoch': '18.75'}
{'train_runtime': '302.2', 'train_samples_per_second': '7.941', 'train_steps_per_second': '0.993', 'train_loss': '1.767', 'epoch': '18.75'}

[I 2026-05-30 15:45:41,053] Trial 9 finished with value: 1.722070336341858 and parameters: {'lora_r': 4, 'lora_alpha': 32, 'lora_dropout': 0.08570320022594267, 'learning_rate': 1.698030404080942e-05, 'warmup_ratio': 0.06301689089443885, 'weight_decay': 0.03498608886967613}. Best is trial 8 with value: 1.70637047290802.

Best run: BestRun(run_id='8', objective=1.70637047290802, hyperparameters={'lora_r': 4, 'lora_alpha': 16, 'lora_dropout': 0.13482101379864803, 'learning_rate': 3.48576351528276e-05, 'warmup_ratio': 0.06349163207497396, 'weight_decay': 0.024825698786720952}, run_summary=None)
Best hyperparameters: {'lora_r': 4, 'lora_alpha': 16, 'lora_dropout': 0.13482101379864803, 'learning_rate': 3.48576351528276e-05, 'warmup_ratio': 0.06349163207497396, 'weight_decay': 0.024825698786720952}

In [ ]:
Best hyperparameters: {'lora_r': 8, 'lora_alpha': 32, 'lora_dropout': 0.14527575281065663, 'learning_rate': 1.5520566449238817e-05, 'warmup_ratio': 0.034256172553320086, 'weight_decay': 0.005597585923559124}

In [ ]:
wandb.init()

In [ ]:
# Apply best hyperparameters
for param, value in best_run.hyperparameters.items():
    setattr(trainer.args, param, value)

# Re-init model with the best LoRA params (stored in _current_lora_params)
_current_lora_params["lora_r"]       = best_run.hyperparameters["lora_r"]
_current_lora_params["lora_alpha"]   = best_run.hyperparameters["lora_alpha"]
_current_lora_params["lora_dropout"] = best_run.hyperparameters["lora_dropout"]
trainer.model = model_init(None)
trainer.args.max_steps = 300
# trainer.train(resume_from_checkpoint=True)
# trainer.train()

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

In [ ]:
# Your selected best hyperparameters (with r=16 to train ~1.18% of params)
final_hyperparameters = {
    'lora_r': 16,
    'lora_alpha': 32,
    'lora_dropout': 0.13482101379864803,
    'learning_rate': 3.48576351528276e-05,
    'warmup_ratio': 0.06349163207497396,
    'weight_decay': 0.024825698786720952
}

# 1. Fresh SFTConfig with WandB disabled and 8-bit optimizer
final_training_args = SFTConfig(
    output_dir="/content/drive/MyDrive/Msc/models/Qwen-FT-final",
    # max_steps=1000,
    num_train_epochs=3,

    logging_steps=100,
    save_steps=100,
    eval_strategy="steps",
    eval_steps=100,
    # fp16=True,
    # optim="paged_adamw_8bit",  # Added to save memory and avoid scaler issues
    dataset_text_field="text",
    report_to="none",  # Explicitly disable wandb
    learning_rate=final_hyperparameters['learning_rate'],
    warmup_ratio=final_hyperparameters['warmup_ratio'],
    weight_decay=final_hyperparameters['weight_decay'],
    bf16=torch.cuda.is_available(),
    per_device_train_batch_size=2,   # The number of samples processed at once per GPU. (Try 1 or 2).
    gradient_accumulation_steps=4,   # Number of steps to accumulate gradients before updating weights.
    gradient_checkpointing=True,     # Saves VRAM by discarding intermediate activations and recomputing them.
    fp16=False,
    optim="adamw_torch",
)

# 2. Fresh LoRA Config
final_peft_config = LoraConfig(
    r=final_hyperparameters['lora_r'],
    lora_alpha=final_hyperparameters['lora_alpha'],
    lora_dropout=final_hyperparameters['lora_dropout'],
    # target_modules="all-linear",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
       ],
    bias="none",
    task_type="CAUSAL_LM",
)

# 3. Fresh Model Initialization
print("Loading base model in float16...")
final_base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    # quantization_config=bnb_config,
    # device_map="auto",
    dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    trust_remote_code=True,
    # torch_dtype=torch.float16,  # Force float16 to prevent BFloat16 scaler errors
)
# final_base_model = prepare_model_for_kbit_training(final_base_model)
final_model = get_peft_model(final_base_model, final_peft_config)

# count_lora_parameters(final_model)

# 4. Fresh SFTTrainer
final_trainer = SFTTrainer(
    model=final_model,
    args=final_training_args,
    train_dataset=formatted_dataset["train"],
    eval_dataset=formatted_dataset["test"],
    processing_class=tokenizer,
)

# 5. Train!
print("\nStarting final training with new SFTTrainer...")
final_trainer.train()

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Loading base model in float16...

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Starting final training with new SFTTrainer...

In [8]:
save_path = "/content/drive/MyDrive/Msc/models/Qwen-FT-best4"
final_trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)
print(f"Saved to: {save_path}")

Saved to: /content/drive/MyDrive/Msc/models/Qwen-FT-best3

In [ ]:
def count_lora_parameters(model):
    trainable_params, all_param = model.get_nb_trainable_parameters()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param:.4f}"
    )

# Check the parameters of the loaded LoRA model
count_lora_parameters(trainer.model)

trainable params: 9232384 || all params: 1552946688 || trainable%: 0.5945

### Model Inference
Load the fine-tuned model from Google Drive and test it with a sample question.

In [9]:
from peft import PeftModel
import torch

# Path where the model was saved
model_save_path = "/content/drive/MyDrive/Msc/models/Qwen-FT-best4"

# Load the base model again (using 4-bit for efficiency)
base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    # quantization_config=bnb_config,
    device_map="auto",
)

# Load the fine-tuned LoRA weights
model = PeftModel.from_pretrained(base_model, model_save_path)
model.eval()

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_save_path)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [10]:
def ask_qwen(question):
    messages = [
        {"role": "user", "content": question}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer([text], return_tensors="pt").to("cuda")

    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=True,
            # temperature=0.7,
            # top_p=0.9,
            pad_token_id=tokenizer.pad_token_id
        )

    # Trim the input tokens from the response
    response_ids = [output_ids[len(input_ids):] for input_ids, output_ids in zip(inputs.input_ids, generated_ids)]
    response = tokenizer.batch_decode(response_ids, skip_special_tokens=True)[0]
    return response

# Test it out!
question = "why are the sky blue?"
print(f"Question: {question}")
print(f"Answer: {ask_qwen(question)}")

Question: why are the sky blue?
Answer: השמיים ידועים כ-transparentים וירחנים על ידי גוף השמש שמקושר לתוך האטמוספירה. הפליאה של אור השמש ב trail, המכונה פליאה או ראייה, מונעת את אור החום האזורי. כאשר אור השמש נופל על פני כדור הארץ, חלק מהאור מגיע לכדור הארץ, וחלק נופל לאטמוספירה. חלק מהאור הזה נופל לתוך המים והחומר הלא ספציפי בתוכם, כמו אבק, ולצורך האטמוספירה, והוא מתפרק למחזור חומרי אטמוספרתי. חלק מהאור_remaining מגיע למכונית ומסתובב למעלה, מתרחב ומתפשף. חלק מהאור הזה מגיע לקצה האטמוספירה, ונקרא 'פליאה'. הפלייה הזו מספקת תוצרת זריזה, וניתן לראות אותה בצורת רוחב, וסימונים להיפך. הפליאה הזו עוזרת להגביר את ההבדלים בין הצבעים הנמוכים יותר לרוב, כמו צבעים ברוקים ואפורים, לבין הצבעים גבוהים יותר, כמו כחול, אפור וירח. אז, זה מה שהופך את השמים לבורחנים וירחנים.